### ISSUE TITLE
How to generate the needed files?

### ISSUE THREAD

**Issue by cnksyyy** [dmollaaliod/bioasq-synergy-public#1]
How can I get files like task8b_nnc_model_1024.data-00000-of-00002?

**Comment by dmollaaliod** [comment]
Hi cnksyyy, I can make the files available on Google Drive on Monday. But I suggest that you use our latest version for the Synergy 10 task: https://github.com/dmollaaliod/bioasq10-synergy.

**Comment by dmollaaliod** [comment]
I just realised that the bioasq10-synergy repository is not yet public... if you can wait a little, I'll make it public in the next couple of weeks.

**Comment by dmollaaliod** [comment]
Sorry for the delay... I am still to make the bioasq10-synergy repository public. In the meantime, I have uploaded the files for this repository here: https://drive.google.com/drive/folders/1cfq-Kkr9NN57rhobgPHZBofsu3ehyp0b?usp=sharing
